version: "3.8"
name: "university"
services:
  db:
    image: postgres:15-alpine
    env_file: ./app/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - net-dev
  api:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    command: [ 'python', 'main.py' ]
    depends_on:
      - db
    ports:
      - "80:8000"
    networks:
      - net-dev

volumes:
  pg_data: { }

networks:
  net-dev:
    driver: bridge
